
export const GET_AUTH_URL = 'GET_AUTH_URL'
export const CHECK_URL = 'CHECK_URL'
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS'
export const GET_PLAYLISTS = 'GET_PLAYLISTS'
export const GET_TRACKS = 'GET_TRACKS'
export const GET_ALBUMS_COVER = 'GET_ALBUMS_COVER'
